import os
import telebot
import requests
from github import Github
from openai import OpenAI
from flask import Flask
from threading import Thread

# ======================
# ENV VARIABLES
# ======================

BOT_TOKEN = os.getenv("BOT_TOKEN")
OPENAI_KEY = os.getenv("OPENAI_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

if not BOT_TOKEN or not OPENAI_KEY or not GITHUB_TOKEN:
    raise ValueError("Missing environment variables")

# ======================
# CLIENTS
# ======================

bot = telebot.TeleBot(BOT_TOKEN)
client = OpenAI(api_key=OPENAI_KEY)
g = Github(GITHUB_TOKEN)

# ✅ اسم الريبو الصحيح
repo = g.get_repo("CyberX3662/ju-cyber-gate-bot")

# ======================
# START COMMAND
# ======================

@bot.message_handler(commands=["start"])
def start(message):
    bot.reply_to(
        message,
        "👋 أهلاً بك!\n\n"
        "أرسل ملف PDF أو Word وسأقوم بتلخيصه + إنشاء فلاش كارد وأسئلة "
        "وسيتم رفعها تلقائياً إلى GitHub."
    )

# ======================
# FILE HANDLER
# ======================

@bot.message_handler(content_types=["document"])
def handle_file(message):
    try:
        bot.reply_to(message, "⏳ جاري قراءة الملف ومعالجته...")

        file_info = bot.get_file(message.document.file_id)
        file_url = f"https://api.telegram.org/file/bot{BOT_TOKEN}/{file_info.file_path}"

        file_bytes = requests.get(file_url).content
        text = file_bytes.decode("utf-8", errors="ignore")[:4000]

        prompt = f"""
Summarize this lecture in Arabic and English.
Create flashcards and quiz questions.

{text}
"""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        content = response.choices[0].message.content

        path = "AutoGenerated/Week.md"

        try:
            old_file = repo.get_contents(path)
            repo.update_file(
                path,
                "Update lecture summary",
                content,
                old_file.sha
            )
        except:
            repo.create_file(
                path,
                "Create lecture summary",
                content
            )

        bot.reply_to(message, "✅ تم إنشاء الملخص والفلاش كارد والأسئلة ورفعها إلى GitHub")

    except Exception as e:
        bot.reply_to(message, f"❌ خطأ:\n{e}")

# ======================
# KEEP ALIVE SERVER
# ======================

app = Flask("")

@app.route("/")
def home():
    return "Bot is running..."

def run():
    app.run(host="0.0.0.0", port=10000)

def keep_alive():
    t = Thread(target=run)
    t.start()

keep_alive()

# ======================
# START BOT
# ======================

bot.infinity_polling(skip_pending=True)
