import os
import telebot
import openai
import requests
from github import Github

BOT_TOKEN = os.getenv("BOT_TOKEN")
OPENAI_KEY = os.getenv("OPENAI_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

openai.api_key = OPENAI_KEY
bot = telebot.TeleBot(BOT_TOKEN)
g = Github(GITHUB_TOKEN)
repo = g.get_repo("CyberX3662/JU-Cyber-Gate")

@bot.message_handler(content_types=["document"])
def handle_file(message):
    file_info = bot.get_file(message.document.file_id)
    file_url = f"https://api.telegram.org/file/bot{BOT_TOKEN}/{file_info.file_path}"

    text = requests.get(file_url).content[:4000].decode(errors="ignore")

    prompt = f"""
Summarize this lecture in Arabic and English.
Create flashcards and quiz questions.

{text}
"""

    res = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role":"user","content":prompt}]
    )

    content = res["choices"][0]["message"]["content"]

    path = "AutoGenerated/Week.md"

    try:
        old = repo.get_contents(path)
        repo.update_file(path, "update", content, old.sha)
    except:
        repo.create_file(path, "create", content)

    bot.reply_to(message, "✅ تم إنشاء الملخص والفلاش كارد ورفعها إلى GitHub")

bot.infinity_polling()
